// Generated by Wrangler on Sat Jun 29 2024 22:52:52 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface Env {}
